# baseurl = ""
languageCode = "en"
title = ""
theme = "tiny"
disqusShortname = ""
googleAnalytics = false

disableKinds = ["taxonomyTerm"]

[taxonomies]
tag = "tags"
category = "categories"

[params]
subtitle = ""
description = ""
author = ""
sharingicons = true
latestpostcount = 5
dateformfull = "January 2, 2006"
dateform = "Jan 2, 2006"
about = ""
license = "http://creativecommons.org/licenses/by-nc/4.0/"
licenseName = "CC BY-NC 4.0"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

[[params.project]]
name = "project"
url = "project url"
